

services:
  app:
    image: learnzy:latest
    ports:
      - "8082:8082"
    build: .
    container_name: learnzy-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/learnzydb
      SPRING_DATASOURCE_USERNAME: learnzyuser
      SPRING_DATASOURCE_PASSWORD: learnzy123
      ELASTIC_URL: http://elasticsearch:9200
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: myelasticpassword
    depends_on:
      elasticsearch:
        condition: service_healthy
      db:
        condition: service_started


  db:
    image: postgres:latest
    container_name: learnzy_db
    environment:
      POSTGRES_USER: learnzyuser
      POSTGRES_PASSWORD: learnzy123
      POSTGRES_DB: learnzydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.12
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=myelasticpassword
      - xpack.security.enabled=false
      - network.host=0.0.0.0
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep '\"status\"'" ]
      interval: 5s
      retries: 12
    ports:
      - "9200:9200"

volumes:
  postgres_data: