server:
  port: 8082


spring:
  application:
    name: Learnzy
  datasource:
    url: jdbc:postgresql://localhost:5432/learnzy
    username: adminuser
    password: adminuser
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  elasticsearch:
    uris: http://localhost:9200/
    username: elastic
    password: 6JA9bIBGgR9OI5aaRjLz
  seed-data:
    file-path: courses.json
  security:
    jwt:
      secret-key: $backendproject-learnzy-jan-2026
      expiration: 86400
