spring:
  application:
    name: Learnzy
  server:
    port: 8082
  datasource:
    url: jdbc:postgresql://localhost:5432/learnzy
    username: adminuser
    password: adminuser
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  seed-data:
    file-path: courses.json
